language: go
go:
- 1.9.4
before_script:
- mv ../../Strabox ../../strabox
script:
# Build the project
- make
# Run the default/example engine
- make simulate
notifications:
  on_success: change
  on_failure: change