[Caravela]
Simulation = true
[Caravela.DiscoveryBackend]
Backend = "chord-smart"    # chord-random, chord-smart
    [Caravela.DiscoveryBackend.SmartChordBackend]
    SupplyingInterval = "30s"
    SpreadOffersInterval = "30s"
    RefreshingInterval = "30s"
    [Caravela.DiscoveryBackend.RandomChordBackend]
    RandBackendMaxRetries = 4
[Caravela.Resources]
    [[Caravela.Resources.CPUPowers]]
    Value = 0
    Percentage = 100
        [[Caravela.Resources.CPUPowers.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUPowers.CPUCores.RAMs]]
            Value = 256
            Percentage = 50
            [[Caravela.Resources.CPUPowers.CPUCores.RAMs]]
            Value = 512
            Percentage = 50
        [[Caravela.Resources.CPUPowers.CPUCores]]
        Value = 2
        Percentage = 50
            [[Caravela.Resources.CPUPowers.CPUCores.RAMs]]
            Value = 256
            Percentage = 50
            [[Caravela.Resources.CPUPowers.CPUCores.RAMs]]
            Value = 512
            Percentage = 50

[Overlay]
    [Overlay.Chord]
    NumSuccessors = 3
    HashSizeBits = 128