[Caravela]
Simulation = true
CPUSlices = 1
CPUOvercommit = 100
MemoryOvercommit = 100
SchedulingPolicy = "binpack"
[Caravela.DiscoveryBackend]
Backend = "chord-single-offer"    # chord-random, chord-single-offer, chord-multiple-offers, swarm
    [Caravela.DiscoveryBackend.OfferingChordBackend]
    SpreadOffersInterval = "5m"
    RefreshingInterval = "5m"
    # Debug performance flags
    SpreadOffers = true
    SpreadPartitionsState = true
    GUIDEstimatedNetworkSize = 5000
    GUIDScaleFactor = 3
    [Caravela.DiscoveryBackend.RandomChordBackend]
    RandBackendMaxRetries = 4
[Caravela.Resources]
    [[Caravela.Resources.CPUClasses]]
    Value = 0
    Percentage = 70
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 256
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 2
        Percentage = 30
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 4
        Percentage = 20
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 2048
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 25
    [[Caravela.Resources.CPUClasses]]
    Value = 1
    Percentage = 30
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 256
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 2
        Percentage = 30
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 4
        Percentage = 20
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 2048
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 25

[Overlay]
    [Overlay.Chord]
    NumSuccessors = 3
    HashSizeBits = 128