[Caravela]
RefreshingInterval = "30s"
OffersStrategy = "chordDefault"
Simulation = true
    # Cpu Cores Partitions
    [[Caravela.CpuCoresPartitions]]
    Cores = 1
    Percentage = 10
    [[Caravela.CpuCoresPartitions]]
    Cores = 2
    Percentage = 40
    [[Caravela.CpuCoresPartitions]]
    Cores = 4
    Percentage = 30
    [[Caravela.CpuCoresPartitions]]
    Cores = 8
    Percentage = 20
    # Ram Partitions
    [[Caravela.RamPartitions]]
    Ram = 128
    Percentage = 25
    [[Caravela.RamPartitions]]
    Ram = 256
    Percentage = 25
    [[Caravela.RamPartitions]]
    Ram = 512
    Percentage = 25
    [[Caravela.RamPartitions]]
    Ram = 1024
    Percentage = 25

[Overlay]
ChordNumSuccessors = 3
ChordHashSizeBits = 128