[Caravela]
Simulation = true
CPUSlices = 1
CPUOvercommit = 100
MemoryOvercommit = 100
SchedulingPolicy = "binpack"
[Caravela.DiscoveryBackend]
    [Caravela.DiscoveryBackend.OfferingChordBackend]
    SpreadOffersInterval = "1m"
    RefreshingInterval = "15m"
    MaxPartitionsSearch = 1
    # Debug performance flags
    SpreadOffers = false
    SpreadPartitionsState = false
    PartitionsStateBufferSize = 25
    PseudoSuperPeers = true
    GUIDEstimatedNetworkSize = 16383
    GUIDScaleFactor = 7
    [Caravela.DiscoveryBackend.RandomChordBackend]
    RandBackendMaxRetries = 3
[Caravela.Resources]
    [[Caravela.Resources.CPUClasses]]
    Value = 0
    Percentage = 65
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 256
            Percentage = 100
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 2
        Percentage = 35
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 65
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 35
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 4
        Percentage = 15
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 2048
            Percentage = 35
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 15
    [[Caravela.Resources.CPUClasses]]
    Value = 1
    Percentage = 35
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 256
            Percentage = 100
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 2
        Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 65
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 35
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 4
        Percentage = 15
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 2048
            Percentage = 65
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 35
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 8
        Percentage = 10
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 65
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 8198
            Percentage = 35

[Overlay]
    [Overlay.Chord]
    NumSuccessors = 3
    HashSizeBits = 128