[Caravela]
Simulation = true
CPUSlices = 1
CPUOvercommit = 100
MemoryOvercommit = 100
SchedulingPolicy = "binpack"
[Caravela.DiscoveryBackend]
    [Caravela.DiscoveryBackend.OfferingChordBackend]
    SpreadOffersInterval = "2m30s"
    RefreshingInterval = "7m30s"
    # Debug performance flags
    SpreadOffers = true
    SpreadPartitionsState = true
    PartitionsStateBufferSize = 10
    PseudoSuperPeers = true
    GUIDEstimatedNetworkSize = 20000
    GUIDScaleFactor = 5
    [Caravela.DiscoveryBackend.RandomChordBackend]
    RandBackendMaxRetries = 3
[Caravela.Resources]
    [[Caravela.Resources.CPUClasses]]
    Value = 0
    Percentage = 75
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 256
            Percentage = 100
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 2
        Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 4
        Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 2048
            Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 25
    [[Caravela.Resources.CPUClasses]]
    Value = 1
    Percentage = 25
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 1
        Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 256
            Percentage = 100
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 2
        Percentage = 25
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 512
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 1024
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 4
        Percentage = 13
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 2048
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 50
        [[Caravela.Resources.CPUClasses.CPUCores]]
        Value = 8
        Percentage = 12
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 4096
            Percentage = 50
            [[Caravela.Resources.CPUClasses.CPUCores.Memory]]
            Value = 8198
            Percentage = 50

[Overlay]
    [Overlay.Chord]
    NumSuccessors = 3
    HashSizeBits = 160