NumberOfNodes = 5000
TickInterval = "20s"
MaxTicks = 45
Multithread = true
DiscoveryBackends = ["chord-single-offer", "chord-multiple-offer", "chord-random", "swarm"]
RequestFeeder = "random"            # random
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, "real", partition-fit
    [ResourcesGenerator.StaticResources]
    CPUClass = 1
    CPUs = 4
    RAM = 4048