NumberOfNodes = 50000
TickInterval = "20s"
MaxTicks = 63
Multithread = true
DiscoveryBackends = ["chord-single-offer", "chord-multiple-offer", "chord-random"]
RequestFeeder = "random"            # random
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, "real", partition-fit
    [ResourcesGenerator.StaticResources]
    CPUClass = 1
    CPUs = 2
    RAM = 2048