NumberOfNodes = 50000
TickInterval = "10s"
MaxTicks = 30
Multithread = true
RequestFeeder = "random"
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "static"       # static, real, partition-aware
    [ResourcesGenerator.StaticResources]
    CPUs = 1
    RAM = 256