NumberOfNodes = 100000
TickInterval = "20s"
MaxTicks = 350
Multithread = true
DiscoveryBackends = ["chord-single-offer", "chord-random"]
RequestFeeder = "json"            # random, json
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, "real", partition-fit
    [ResourcesGenerator.StaticResources]
    CPUClass = 0
    CPUs = 4
    Memory = 4048