NumberOfNodes = 10000
TickInterval = "20s"
MaxTicks = 175
Multithread = true
DiscoveryBackends = ["chord-single-offer", "chord-random"]  # chord-random, chord-single-offer, chord-multiple-offer, swarm
OutDirectoryPath = "out"
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[RequestFeeder]
RequestFeeder = "random"    # random, json
    DeployRequestsRate = [3.5, 4.5, 3.0, 3.5, 4.0, 2.0, 0.0, 0.0, 1.5, 1.5, 2.5, 5.0, 3.5]
    StopRequestsRate =   [0.0, 0.5, 0.0, 0.5, 0.0, 2.5, 3.5, 3.5, 3.5, 2.5, 1.5, 0.0, 0.0]
    # CPU Class 0
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 1
    Memory =  256
    Percentage = 20
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 2
    Memory =  1500
    Percentage = 20
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 3
    Memory =  2500
    Percentage = 10
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 4
    Memory =  3500
    Percentage = 15
    # CPU Class 1
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 1
    CPUs = 1
    Memory =  512
    Percentage = 20
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 1
    CPUs = 3
    Memory =  2048
    Percentage = 10
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 1
    CPUs = 6
    Memory =  5500
    Percentage = 5

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, partition-fit
    [ResourcesGenerator.StaticResources]
    CPUClass = 0
    CPUs = 4
    Memory = 4048

[ChordMock]
SpeedupNodes = 300