NumberOfNodes = 10000
TickInterval = "20s"
MaxTicks = 60
Multithread = true
DiscoveryBackends = ["chord-single-offer", "chord-random", "swarm"]
RequestFeeder = "random"            # random
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, "real", partition-fit
    [ResourcesGenerator.StaticResources]
    CPUClass = 0
    CPUs = 4
    Memory = 4048