NumberOfNodes = 50000
TickInterval = "10s"
MaxTicks = 35
Multithread = true
RequestFeeder = "random"
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "real"       # static, real, partition-aware
    [ResourcesGenerator.StaticResources]
    CPUs = 2
    RAM = 512