NumberOfNodes = 50000
TickInterval = "10s"
MaxTicks = 15
Multithread = true
RequestFeeder = "random"
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "static"       # static, real, partition-aware
    [ResourcesGenerator.StaticResources]
    CPUs = 2
    RAM = 1024