NumberOfNodes = 10000
TickInterval = "20s"
MaxTicks = 360
Multithread = true
DiscoveryBackends = ["chord-multiple-offer-updates", "chord-random", "swarm"]  # chord-random, chord-single-offer, chord-multiple-offer, swarm
OutDirectoryPath = "out"
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[RequestFeeder]
RequestFeeder = "random"    # random, json
    DeployRequestsRate = [2.5, 3.0, 2.0, 2.5, 3.5, 2.5, 2.5, 2.0, 1.5, 1.5, 2.0, 1.5, 2.0, 1.5, 1.0, 2.0, 1.5, 2.5, 3.5, 2.0, 2.0, 2.0, 1.5, 2.0, 3.0]
    StopRequestsRate =   [0.0, 1.0, 0.5, 0.5, 0.5, 1.5, 1.0, 1.5, 1.5, 1.5, 1.0, 1.5, 2.0, 2.0, 1.0, 1.5, 1.0, 1.5, 1.0, 0.5, 1.0, 0.5, 0.5, 0.5, 0.5]
    # CPU Class 0
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 1
    Memory =  200
    Percentage = 15
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 1
    Memory =  600
    Percentage = 5
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 2
    Memory =  1200
    Percentage = 10
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 2
    Memory =  1600
    Percentage = 10
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 2
    Memory =  2800
    Percentage = 10
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 0
    CPUs = 4
    Memory =  3000
    Percentage = 15
    # CPU Class 1
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 1
    CPUs = 1
    Memory =  750
    Percentage = 20
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 1
    CPUs = 2
    Memory =  2500
    Percentage = 10
    [[RequestFeeder.RequestsProfile]]
    CPUClass = 1
    CPUs = 6
    Memory =  5000
    Percentage = 5

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, partition-fit

[ChordMock]
SpeedupNodes = 300