NumberOfNodes = 50000
TickInterval = "20s"
MaxTicks = 45
Multithread = true
DiscoveryBackends = ["chord-single-offer", "chord-multiple-offer", "chord-random"]
RequestFeeder = "random"            # random
SimulatorLogLevel = "info"
CaravelaLogLevel = "info"

[ResourcesGenerator]
ResourceGenerator = "partition-fit" # static, real, partition-fit
    [ResourcesGenerator.StaticResources]
    CPUs = 2
    RAM = 1024